
default: &default
  adapter: postgresql
  encoding: unicode
  username: "postgres"
  password: "bernabas"


development:
  <<: *default
  database: rails_blog_api_development
  # database: Blog_App_development
  # host: localhost
  # username: postgres
  # password: Charles44..


test:
  <<: *default
  database: rails_blog_api_test
  # <<: *default
  # database: Blog_App_test
  # host: localhost
  # username: postgres
  # password: Charles44..

production:
  <<: *default
  database: rails_blog_production
  username: root
  # database: Blog_App_production
  # host: localhost
  # username: postgres
  # password: Charles44..
